from __future__ import annotations

import html
import re
from typing import Dict, Optional

import pandas as pd


CATEGORY_ORDER = [
    "INDICES",
    "EU SECTORS",
    "US SECTORS",
    "STYLE ETFs",
    "BOND ETFs",
    "CURRENCIES",
    "COMMODITIES",
]


def markdown_to_basic_html(
    markdown_text: str,
    summary_df: Optional[pd.DataFrame] = None,
    universe: Optional[Dict[str, Dict[str, str]]] = None,
) -> str:
    universe = universe or {}
    asset_names = _asset_names(universe)

    lines = markdown_text.splitlines()
    out = [
        "<html><body style='font-family:Arial,sans-serif;line-height:1.6;color:#333;max-width:960px;margin:0 auto;padding:20px;'>",
        "<div style='color:#0000EB;font-size:28px;text-align:center;margin-bottom:24px;font-weight:700;'>GLOBAL MARKET UPDATE</div>",
    ]

    for line in lines:
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            out.append(
                f"<h2 style='color:#0000EB;font-size:20px;margin-top:26px;margin-bottom:12px;padding-bottom:5px;border-bottom:1px solid #ccc;'>{html.escape(line[3:])}</h2>"
            )
            continue
        if line.startswith("- "):
            out.append(f"<p style='margin:4px 0 4px 12px;'>- {_highlight_assets(line[2:], asset_names)}</p>")
            continue
        if line.strip() == "":
            out.append("<br/>")
            continue
        out.append(f"<p style='margin-bottom:12px;text-align:justify;'>{_highlight_assets(line, asset_names)}</p>")

    if summary_df is not None and not summary_df.empty:
        out.append("<h2 style='color:#0000EB;font-size:20px;margin-top:26px;margin-bottom:12px;padding-bottom:5px;border-bottom:1px solid #ccc;'>PERFORMANCE SUMMARY</h2>")
        out.append(_performance_table_html(summary_df, universe))

    out.append(
        "<div style='margin-top:34px;font-size:12px;color:#666;border-top:1px solid #ccc;padding-top:10px;'>"
        "This report has been generated by Global Market Monitor."
        "</div>"
    )
    out.append("</body></html>")
    return "\n".join(out)


def _asset_names(universe: Dict[str, Dict[str, str]]) -> list[str]:
    names = []
    for category_assets in universe.values():
        names.extend(category_assets.keys())
    names.extend(["US 2s10s Slope (bps)", "US IG Spread Proxy", "US HY Spread Proxy", "EU IG Spread Proxy", "EU HY Spread Proxy"])
    return sorted(set(names), key=len, reverse=True)


def _highlight_assets(text: str, assets: list[str]) -> str:
    escaped = html.escape(text)
    escaped = escaped.replace("**", "<strong>", 1).replace("**", "</strong>", 1) if "**" in escaped else escaped

    for asset in assets:
        pattern = r"(?<![\w>])" + re.escape(html.escape(asset)) + r"(?![\w<])"
        escaped = re.sub(pattern, f"<span style='font-weight:700;'>{html.escape(asset)}</span>", escaped)

    escaped = _remove_redundant_adverbs(escaped)
    return escaped


def _remove_redundant_adverbs(text: str) -> str:
    movement_verbs = [
        "rose", "gained", "increased", "advanced", "climbed", "strengthened", "appreciated", "fell", "declined", "decreased", "retreated", "dropped", "weakened", "slid", "eased"
    ]
    adverbs = [
        "marginally", "fractionally", "slightly", "modestly", "somewhat", "moderately", "notably", "significantly", "substantially", "sharply", "dramatically"
    ]
    out = text
    for v in movement_verbs:
        for a in adverbs:
            out = re.sub(rf"\b{re.escape(v)}\s+{re.escape(a)}\b", v, out, flags=re.IGNORECASE)
    return out


def _performance_table_html(summary_df: pd.DataFrame, universe: Dict[str, Dict[str, str]]) -> str:
    html_rows = [
        "<table style='width:100%;border-collapse:collapse;margin:18px 0;font-size:14px;'>",
        "<tr><th style='background:#0000EB;color:#fff;text-align:left;padding:10px;'>Index/Asset</th><th style='background:#0000EB;color:#fff;text-align:right;padding:10px;'>Change (%)</th><th style='background:#0000EB;color:#fff;text-align:right;padding:10px;'>Vol (%)</th><th style='background:#0000EB;color:#fff;text-align:right;padding:10px;'>Max DD (%)</th></tr>",
    ]

    for cat in CATEGORY_ORDER:
        cat_assets = list((universe.get(cat) or {}).keys())
        subset = summary_df.loc[summary_df.index.intersection(cat_assets)]
        if subset.empty:
            continue

        html_rows.append(
            f"<tr><td colspan='4' style='background:#e6e6e6;font-weight:700;padding:8px;border:1px solid #ddd;'>{html.escape(cat.title())}</td></tr>"
        )

        for asset, row in subset.sort_values("Total Return %", ascending=False).iterrows():
            ret = float(row["Total Return %"])
            vol = float(row["Volatility %"])
            mdd = float(row["Max Drawdown %"])
            color = "green" if ret >= 0 else "red"
            sign = "+" if ret >= 0 else ""
            html_rows.append(
                "<tr>"
                f"<td style='border:1px solid #ddd;padding:8px;'><span style='font-weight:700;'>{html.escape(asset)}</span></td>"
                f"<td style='border:1px solid #ddd;padding:8px;text-align:right;color:{color};'>{sign}{ret:.2f}%</td>"
                f"<td style='border:1px solid #ddd;padding:8px;text-align:right;'>{vol:.2f}%</td>"
                f"<td style='border:1px solid #ddd;padding:8px;text-align:right;'>{mdd:.2f}%</td>"
                "</tr>"
            )

    html_rows.append("</table>")
    return "\n".join(html_rows)
